services:
  dms:
    image: ghcr.io/docker-mailserver/docker-mailserver:14.0.0
    container_name: dms
    hostname: mx.example.com
    env_file: mailserver.env
    # ./acme-deploy.sh mx.example.com mailserver /tmp/dms/custom-certs "supervisorctl restart postfix && supervisorctl restart dovecot"
    environment:
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/mx.example.com/full.pem
      - SSL_KEY_PATH=/tmp/dms/custom-certs/mx.example.com/key.pem
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      # - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      # - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    labels:
      - sh.acme.autoload.container=mailserver
    volumes:
      - ./private/dms/mail/:/var/mail/
      - ./private/dms/mail-state/:/var/mail-state/
      - ./var/log/dms/:/var/log/mail/
      - ./var/log/dms-supervisor/:/var/log/supervisor/
      - ./private/lib/dms/config/:/tmp/docker-mailserver/
      - ./var/lib/dms/ssl/:/tmp/dms/custom-certs/
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
        aliases:
          - imap.example.com
          - smtp.example.com
    # resides on encrypted volume
    restart: "no"
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      interval: 300s
      timeout: 3s
      retries: 0
  radicale:
    image: tomsquest/docker-radicale:3.3.0.1
    container_name: radicale
    environment:
      - TAKE_FILE_OWNERSHIP=false
    volumes:
      - ./private/lib/radicale/:/data/
      - ./etc/radicale/config.ini:/config/config:ro
    restart: "no"
    healthcheck:
      test: "curl --fail http://localhost:5232 || exit 1"
      interval: 300s
      retries: 3
  infcloud:
    image: waja/infcloud:0.13.1-16
    container_name: infcloud
    volumes:
      - ./etc/infcloud/config/:/srv/infcloud/config/
    restart: "no"
  roundcube:
    image: roundcube/roundcubemail:1.6.9-apache
    container_name: roundcube
    environment:
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.example.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://smtp.example.com
      - ROUNDCUBEMAIL_SMTP_PORT=465
      - ROUNDCUBEMAIL_USERNAME_DOMAIN=example.com
      - ROUNDCUBEMAIL_REQUEST_PATH=/
      - ROUNDCUBEMAIL_INSTALL_PLUGINS=1
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_COMPOSER_PLUGINS=roundcube/carddav,johndoh/contextmenu,weird-birds/thunderbird_labels,texxasrulez/persistent_login
      - ROUNDCUBEMAIL_PLUGINS=archive,emoticons,filesystem_attachments,jqueryui,managesieve,markasjunk,newmail_notifier,vcard_attachments,zipdownload,carddav,contextmenu,thunderbird_labels,persistent_login
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=20000000
    volumes:
      - ./etc/roundcube/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./var/www/roundcube/:/var/www/html/
      - ./private/lib/roundcube/config/:/var/roundcube/config/
      - ./private/lib/roundcube/db/:/var/roundcube/db/
      - ./var/tmp/roundcube/:/tmp/roundcube-temp/
      - ./var/log/roundcube/:/var/log/apache2
    restart: "no"
    entrypoint: []
    command: sh -c "a2enmod remoteip && exec /docker-entrypoint.sh apache2-foreground"
    logging:
      driver: journald
      options:
        tag: roundcube
  autodiscover:
    image: monogramm/autodiscover-email-settings:66c144e
    container_name: autodiscover
    environment:
      - COMPANY_NAME=example.com
      - SUPPORT_URL=https://autoconfig.example.com
      - DOMAIN=example.com
      - IMAP_HOST=imap.example.com
      - IMAP_PORT=993
      - IMAP_SOCKET=SSL
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=465
      - SMTP_SOCKET=SSL
    restart: unless-stopped
