services:
  acme-sh:
    image: neilpang/acme.sh:3.0.9
    container_name: acme-sh
    volumes:
      - ./var/lib/acme-sh:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    command: daemon
    stdin_open: true
    tty: true
    restart: unless-stopped
  nginx:
    image: nginx:1.27.2-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    labels:
      - sh.acme.autoload.container=nginx
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./var/lib/nginx/ssl:/etc/nginx/ssl
      - ./var/cache/nginx:/var/cache/nginx
      - ./var/run/nginx:/var/run
      - ./var/log/nginx:/var/log/nginx
      - ./var/www/nginx:/var/www
    networks:
      default:
        aliases:
          - mail.example.com
